### Create new user
POST http://localhost:3030/users
Content-Type: application/json

{
  "username": "a",
  "displayname": "a",
  "email": "typedsi@gmail.com",
  "password": "a"
}

### Login
POST http://localhost:3030/authentication
Content-Type: application/json

{
  "email": "farrelld@gmail.com",
  "password": "DesPatates",
  "strategy": "local"
}
